apiVersion: apps/v1
kind: Deployment
metadata:
 name: angular-deployment
 namespace: mahmood
spec:
 replicas: 2
 selector:
  matchLabels:
   app: angular
 template:
  metadata:
   labels:
    app: angular
  spec:
   containers:
    - name: frontend
      image: mahmoodabuawwad/frontend
      env:
      - name: API_URL
        valueFrom:
         configMapKeyRef:
          name: angular-config
          key: API_URL
      - name: PORT
        valueFrom:
         configMapKeyRef:
          name: angular-config
          key: PORT
      imagePullPolicy: Always
      ports:
       - containerPort: 80
