apiVersion: apps/v1
kind: Deployment
metadata:
 name: angular-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
   app: angular 
 template:
  metadata:
   labels:
    app: angular
  spec:
   containers:
    - name: frontend
      image: angular-app
      ports: 
       - containerPort: 80
