apiVersion: v1
kind: Service
metadata:
 labels:
  service-label-key: angular
 name: frontend-service
spec: 
 type: NodePort 
 ports:
 - port: 80
   protocol: TCP
   targetPort: 80
 selector:
  app: angular 
