apiVersion: apps/v1
kind: Deployment
metadata:
 name: angular-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
   app: angular
 template:
  metadata:
   labels:
    app: angular
  spec:
   containers:
    - name: frontend
      image: mahmoodabuawwad/frontend
      env:
      - name: API_URL
        value: "192.168.205.155"
      - name: PORT  # desired in flask-service.yaml
        value: "30007"
      imagePullPolicy: Always
      ports:
       - containerPort: 80
~                                                                                         
~                                                                                         
~                                                                                         
~                                                                                         
~                                                                                         
~                                                                                         
~                                                                                         
~                        
